name: java-maven-snap-hello-world
version: '1.0.0'
summary: Hello World java maven
description: |
  Simple Hello World delivered with java in snap package.

apps:
  helloworld:
    command: ../parts/java-maven-snap-hello-world/build/target/dist/bin/hello-world.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    aliases: [helloworld]

parts:
  java-maven-snap-hello-world:
    plugin: maven
    source: .
    maven-options: [package]
    stage-packages: [openjdk-8-jre]
